#YAML file containing configuration variables required for the GeneSys pipeline.

#Root output directory of the pipeline.
OUTDIR: "/home/james/Desktop/Projects/GeneSys/Proc_Data/JB230212_GeneSys_Run"

#Path to the bowtie2 reference index files. 
BOWTIE2_IDX: "idx" 

#List of target chromosomes to process:
CHROMOSOMES:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chrX
  - chrY

####### DATA SECTION ########
#Paths to FASTQ files. 
#Dictionary where SAMPLES key contains sample name as keys with R1 and R2 keys that contain paths to the respective FASTQ.

FASTQ:
  SAMPLES:
    sample1:
      R1: "r1.txt"
      R2: "r2.txt"

